### ISSUE TITLE
Move Validated<T> to this package

### ISSUE THREAD

**Issue by davidfowl** [DamianEdwards/MinimalValidation#7]
Move [this](https://github.com/DamianEdwards/MinimalApiPlayground/blob/a043846c73a5fef438a2df35b63f15901ff65840/src/MinimalApiPlayground/Properties/ValidatedOfT.cs#L10) here.

**Comment by DamianEdwards** [comment]
Yep my intent is to actually create a _MinimalValidation.AspNetCore_ package and put it in there, given the dependency on `HttpContext`.

**Comment by DamianEdwards** [comment]
Done.
